version: '1.0'
services:
  app:
    build: ./app
    volumes:
      - ./app/flaskapp:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl:/etc/nginx/ssl
      - socket:/tmp

volumes:
  socket: